# Generated by Django 4.2.4 on 2023-09-27 14:15
from django.conf import settings
from django.db import migrations


def create_social_apps(apps, schema_editor):
    SocialApp = apps.get_model('socialaccount', 'SocialApp')
    Site = apps.get_model('sites', 'Site')
    site = Site.objects.get(
        id=settings.SITE_ID
    )
    for app_provider, app_data in settings.SOCIALACCOUNT_PROVIDERS.items():
        try:
            provider = SocialApp.objects.get(provider=app_provider)
            print(f"Got provider back: {provider}")
        except SocialApp.DoesNotExist:
            print(f"creating default allauth social app for for {app_provider}")
            app = SocialApp.objects.create(provider=app_provider, name=app_provider, client_id="Change Me")
            app.sites.add(site)


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
        ("socialaccount", "0005_socialtoken_nullable_app"),
    ]

    operations = [
        migrations.RunPython(create_social_apps, migrations.RunPython.noop),
    ]
