# Generated by Django 4.2.3 on 2023-08-25 14:21
import json

from django.core.serializers.json import DjangoJSONEncoder
from django.db import migrations, models


def convert_to_streamfield(apps, schema_editor):
    ContentPage = apps.get_model("content", "ContentPage")
    BlogPage = apps.get_model("content", "BlogPage")
    for migrated_model_cls in [ContentPage, BlogPage]:
        for page in migrated_model_cls.objects.all():
            page.body = json.dumps(
                [{"type": "paragraph", "value": page.body}],
                cls=DjangoJSONEncoder
            )
            page.save()


def convert_to_richtext(apps, schema_editor):
    ContentPage = apps.get_model("content", "ContentPage")
    BlogPage = apps.get_model("content", "BlogPage")
    for migrated_model_cls in [ContentPage, BlogPage]:
        for page in migrated_model_cls.objects.all():
            if page.body:
                stream = json.loads(page.body)
                page.body = "".join([
                    child["value"] for child in stream
                    if child["type"] == "paragraph"
                ])
                page.save()

class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            convert_to_streamfield,
            convert_to_richtext,
        ),
    ]
