# Generated by Django 4.2.3 on 2023-08-25 14:24

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models

import apps.content.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_convert_stream_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogindexpage",
            name="social_image",
            field=models.ImageField(
                blank=True, help_text="The image to use in social sharing metadata.", null=True, upload_to=""
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="social_image",
            field=models.ImageField(
                blank=True, help_text="The image to use in social sharing metadata.", null=True, upload_to=""
            ),
        ),
        migrations.AddField(
            model_name="contentpage",
            name="social_image",
            field=models.ImageField(
                blank=True, help_text="The image to use in social sharing metadata.", null=True, upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    ("caption", apps.content.blocks.CaptionBlock()),
                    ("html", wagtail.blocks.RawHTMLBlock()),
                ],
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="contentpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    ("caption", apps.content.blocks.CaptionBlock()),
                    ("html", wagtail.blocks.RawHTMLBlock()),
                ],
                use_json_field=True,
            ),
        ),
    ]
