# Generated by Django 4.2.4 on 2023-09-07 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("djstripe", "0012_2_8"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("checkout_session_id", models.CharField(db_index=True, max_length=100, unique=True)),
                ("is_valid", models.BooleanField(default=True)),
                ("price", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="djstripe.price")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="djstripe.product")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
